name: Snakemake Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  snakemake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Замените на версию Python, которую вы используете

      - name: Install Snakemake
        run: pip install snakemake

      - name: snakemake
        uses: snakemake/snakemake-github-action@v1.25.1
        with:
          directory: .
          snakefile: Snakefile
          args: "--cores 1"
          stagein: ""
          task: "run"
          show-disk-usage-on-error: true

      - name: Push results to gh-pages
        if: success()
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git clone https://github.com/${{ github.repository_owner }}/${{ github.repository }}.git
          cd ${{ github.repository }}
          git checkout gh-pages || git checkout --orphan gh-pages
          cp -r ../dist/* .
          git add .
          git commit -m "Update Snakemake results"
          git push https://github.com/${{ github.repository_owner }}/${{ github.repository }}.git gh-pages
